### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by CornishGuardian** [scottanderson/railroad.studio#3]
Hello, I am trying to use upload and for some reason after working fine for the past few days. I am now incountering this error. Any suggestions? 

Failed to load: InvalidStateError: Failed to execute 'inverse' on 'SVGMatrix': The matrix is not invertible.
Error: Failed to execute 'inverse' on 'SVGMatrix': The matrix is not invertible.
    at l.zoomAtPoint (https://railroad.studio/studio.js:1:14786)
    at l.zoom (https://railroad.studio/studio.js:1:14963)
    at l.publicZoom (https://railroad.studio/studio.js:1:15115)
    at Object.zoom (https://railroad.studio/studio.js:1:21120)
    at new pr (https://railroad.studio/studio.js:1:113787)
    at new Studio (https://railroad.studio/studio.js:1:134874)
    at https://railroad.studio/studio.js:1:188622
    at https://railroad.studio/studio.js:1:179223

**Comment by scottanderson** [comment]
Resolved by adding a guard around the `zoom()` call.
